### PR TITLE
lineColor prop

### LINKED ISSUE #66: Adding documentation for custom line color
I was looking to duplicate the effect for changing the vertical line color, and couldn't find documentation anywhere. After digging around, I realized adding a className for the VerticalTimeline component with this CSS (class_name:before {background: black;}) has the desired effect. Is this already in the documentation, or can it be added? Thanks!

### PR DESCRIPTION
**Pull request by avgupta456**
I added a prop for lineColor, and used CSS variables to update the class. 

closes #66

### CODE REVIEW

**Comment by AndreiPisica** [comment]
why isn't this merged?

**Comment by FUSAKLA** [comment]
+1 I'd like to change dynamically the line color to align with the dark/light theme and using only static CSS without access to the elements does not allow me to do this :/

**Comment by max-deathray** [comment]
+1 I would love this feature also! 💯

**Comment by jorpilo** [comment]
+1 This would be really good, please merge

**Comment by Notaduck** [comment]
@stephane-monnot is this something whic is going to implemented?

**Review by stephane-monnot — APPROVED** [review]

**Pull request merged**
