### PR TITLE
Add single column to the right feature

### PR DESCRIPTION
**Pull request by ShiraNeuman**
I added an option of a single column to the right and updated the documentation.
capture

### CODE REVIEW

**Comment by stephane-monnot** [comment]
Thank you for your contribution. 
Maybe, we can keep backward compatibility by adding and alias '1-column'  => '1-column-left'.

**Comment by Vagahbond** [comment]
Hello,  this feature would be very useful and I'd like to use it, could you please accept this merge request?

**Comment by stephane-monnot** [comment]
I'm waiting modification to keep backward compatibility.

**Comment by stephane-monnot** [comment]
See #80

**Pull request closed without merging**
