### PR TITLE
Add custom classes to the elements inside the VerticalTimelineElement component

### PR DESCRIPTION
**Pull request by karkarn1**
Hello! This is my first time making a pull request, so please let me know if I am doing it right or if I'm missing a step :smile: 

I added 3 new props to the VerticalTimelineElement component:

1. dateClassName: Add a class to the date element
2. iconClassName: Add a class to the icon element
3. textClassName: Add a class to the text container div

Also, since the wrapper div in that component is only here to wrap its content, I replaced it with a Fragment, which removes the unnecessary div when the component is rendered.

Finally, I added keys to the demo code to avoid the React warning about component keys.

### CODE REVIEW

**Comment by killmenot** [comment]
Hi @stephane-monnot Could you please find time to review this PR and merge it if you think it's good enough?

**Comment by AyoubeAkaouch** [comment]
This is exactly what I was looking for, it makes it so much easier.

**Comment by kyleboe** [comment]
Bump 👍

**Comment by stephane-monnot** [comment]
Sorry for the delayed response and thank you for your contribution. Could you provide tests please ?

**Comment by AyoubeAkaouch** [comment]
@karkarn1  Could you please write tests? I need this

**Comment by danielolamide** [comment]
Hi @stephane-monnot is this merge going to be made?

**Comment by stephane-monnot** [comment]
@danielolamide You can check on master branch.

**Pull request closed without merging**
