### PR TITLE
Feature/hide empty content

### PR DESCRIPTION
**Pull request by joeyparis**
This hides the floating white box if no children are passed into the `VerticalTimelineElement` allowing for the timeline to have entries that are just icons or just icons and dates. This probably isn't the most effective way to do this but was the least disruptive to the existing code.

I understand if this becomes an "unwanted behavior" and isn't accepted but I personally found it useful in my use case.

### CODE REVIEW

**Comment by stephane-monnot** [comment]
My suggestions : 
 * Maybe could you rename the class to `vertical-timeline-element--no-children` and put this class to the root element ? 
 * Modify your css selectors : 
.vertical-timeline-element--no-children vertical-timeline-element-content
.vertical-timeline-element--no-children vertical-timeline-element-content::before
* add test to `__tests__/VerticalTimelineElement_test.js` file. For instance : 
```jsx
describe('VerticalTimeline', function () {
  ....
  describe('when children is null', function () {
    it('should have the vertical-timeline-element--no-children classname', function () {
      const component = renderIntoDocument(<VerticalTimelineElement />);
      findRenderedDOMComponentWithClass(component, 'vertical-timeline-element--no-children');
    });

    it('should not have the vertical-timeline-element--no-children classname', function () {
      const component = renderIntoDocument(<VerticalTimelineElement><div>My children</div></VerticalTimelineElement>);
      findRenderedDOMComponentWithClass(component, 'vertical-timeline-element--no-children');
    });
  });
});
```

**Comment by joeyparis** [comment]
Thanks for the suggestions! I have adjusted the CSS classes to match your suggestions.

I am new to testing so I apologize in advance if any of my tests don't follow proper testing conventions.

I also added an example to the demo page, but of course feel free to adjust that example in whatever way you feel is best for the demo.

This should be good to merge now. It is passing all testing including lint.

**Comment by stephane-monnot** [comment]
Good job. Thanks. I will check demo and bump version. It's an old way to test, so I will replace with Enzyme when I have time.

**Comment by stephane-monnot** [comment]
Available on 2.1.1.

**Comment by joeyparis** [comment]
No, thank you! I'm working on a pretty big feature for my project that's all sort of centered around a "timeline" aspect so I'll probably be adding a small handful of features to your timeline component if that's okay with you, otherwise I can just fork my own version.

I'm very new to effectively programming tests but my allocated time for this stretch of my project is pretty large and there are relatively few (and also simple) tests so I can probably fit that transition into my development schedule over the next ~2 weeks.

**Comment by stephane-monnot** [comment]
I'm glad to hear that. I will appreciate your contributions.

**Pull request merged**
